config/routes.rb
Rails.application.routes.draw do
  devise_for :jirolians

  root 'top#index'

  get '/search' => 'top#search'
  resources :posts, expect: [:index] do
    resource :favorite_posts, only: [:create, :destroy]
  end

  resources :jiros, except: [:destroy] do
    resource :business_hours, only: [:edit, :update]
    resource :facilities, only: [:edit, :update]
    resource :menu_items, only: [:edit] do
      member do
        patch 'update_main_menu'
        patch 'update_option_menu'
      end
    end
    resource :posts, only: [:new, :create]
    resource :wanna_eat_statuses, only: [:create, :destroy]
    resource :have_eaten_statuses, only: [:create, :destroy]
  end

  # resources :jirolians, only: [:show] do
  #   resources :posts, only: [:show]
  # end

  get '/jirolians/mypage' => 'jirolians#mypage'
  get '/jirolians/:username' => 'jirolians#show'
  get '/jirolians/:username/edit' => 'jirolians#edit'
  patch '/jirolians/:username' => 'jirolians#update'

  resources :relationships, only: [:create, :destroy]
end

app/models/jiro.rb
# == Schema Information
#
# Table name: jiros
#
#  id                     :bigint           not null, primary key
#  access                 :string(255)
#  address                :string(255)
#  call_timing            :integer
#  how_to_order           :integer
#  hp_url                 :string(255)
#  image                  :string(255)
#  information            :text(65535)
#  is_closed              :boolean
#  is_parking_area        :boolean
#  latitude               :float(24)
#  longitude              :float(24)
#  name                   :string(255)      not null
#  payment_method         :integer
#  phone_number           :string(255)
#  seat_count             :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  registered_jirolian_id :integer
#
class Jiro < ApplicationRecord
  has_one :facility
  has_many :menu_items
  has_many :business_hours
  has_many :wanna_eat_statuses, dependent: :destroy
  has_many :have_eaten_statuses, dependent: :destroy
  has_many :posts, dependent: :destroy

  mount_uploader :image, ImageUploader
  geocoded_by :address

  enum payment_method: {default: 0, only_cash: 1, available_bisides_cash: 2}, _prefix: true
  enum how_to_order: {default: 0, meal_voucher_system: 1, order_system: 2}, _prefix: true
  enum call_timing: {default: 0, submit_meal_voucher: 1, boiled_noodles: 2}, _prefix: true

  validates :name, presence: true
  after_validation :geocode, if: :address_changed?
  # VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0-?\d{4}-?\d{4}\z/.freeze
  # validates :phone_number, format: {with: VALID_PHONE_NUMBER_REGEX}

  def checked_wanna_eat_by?(jirolian)
    wanna_eat_statuses.where(jirolian_id: jirolian.id).exists? if jirolian.present?
  end

  def checked_have_eaten_by?(jirolian)
    have_eaten_statuses.where(jirolian_id: jirolian.id).exists? if jirolian.present?
  end
end

app/controllers/jiros_controller.rb
class JirosController < ApplicationController
  before_action :set_jiro, except: [:new, :create]
  before_action :authenticate_jirolian!, except: [:show]

  def show
    @facility = @jiro.facility
    @table_seasonings = create_table_seasonings_list(@facility) if @facility

    @main_menus = @jiro.menu_items.main_menu
    @toppings_list = create_toppings_list(@main_menus)
    @option_menus = @jiro.menu_items.option_menu

    @business_hour_wdays_list = @jiro.business_hours.group_by(&:wday)

    @posts = Post.where(jiro_id: params[:id])
  end

  def new
    @jiro = Jiro.new
  end

  def create
    ActiveRecord::Base.transaction do
      @jiro = Jiro.create!(create_jiro_params)
    end
    Facility.create(jiro_id: @jiro.id)

    business_hours = []
    (0..6).each do |wday|
      (1..2).each do |category|
        business_hours << BusinessHour.new(wday: wday, category: category, jiro_id: @jiro.id)
      end
    end
    BusinessHour.import(business_hours)

    menu_items = []
    6.times do
      menu_items << MenuItem.new(is_main: true, jiro_id: @jiro.id)
      menu_items << MenuItem.new(is_main: false, jiro_id: @jiro.id)
    end
    MenuItem.import(menu_items)

    redirect_to jiro_path(@jiro)
  rescue StandardError => e
    render action: :new
  end

  def edit; end

  def update
    if @jiro.update(update_jiro_params)
      flash.notice = '更新が完了しました。'
      redirect_to jiro_path(@jiro)
    else
      flash.notice = '更新に失敗しました。'
      render action: :edit
    end
  end

  private

  def set_jiro
    @jiro = Jiro.find(params[:id])
  end

  # @pramas [Facility] facility
  # @return [Array]
  def create_table_seasonings_list(facility)
    [facility.seasoning1, facility.seasoning2, facility.seasoning3, facility.seasoning4,
     facility.seasoning5].uniq
  end

  # @pramas [MainMenu] main_menus
  # @return [Hash] => [integer] key, [Array] value
  def create_toppings_list(main_menus)
    toppings_list = {}
    main_menus.each do |main_menu|
      toppings = [main_menu.topping1, main_menu.topping2, main_menu.topping3, main_menu.topping4, main_menu.topping5,
                  main_menu.topping6, main_menu.topping7]
      toppings_list.store(main_menu.id, toppings)
    end
    toppings_list
  end

  def create_jiro_params
    params.require(:jiro).permit(:name, :address, :access, :is_parking_area, :phone_number, :hp_url, :seat_count,
                                 :payment_method, :how_to_order, :call_timing, :image)
  end

  def update_jiro_params
    params[:jiro].permit(:name, :address, :access, :is_parking_area, :phone_number, :hp_url, :seat_count, :payment_method,
                         :how_to_order, :call_timing, :image)
  end
end

app/helpers/jiros_helper.rb
module JirosHelper
  LUNCH_TIME = 'lunch'.freeze
  DINNER_TIME = 'dinner'.freeze

  # @params [boolean] facility
  # @return [string]
  def exist(facility)
    return '未設定' if facility.nil?

    facility ? '○' : '×'
  end

  # @params [integer] seat_count
  # @return [string]
  def show_waiting_seat(seat_count)
    return '未設定' if seat_count.nil?
    return "○(#{seat_count}人)" if seat_count.positive?
    return '×' if seat_count.zero?
  end

  # @params [Array] table_seasonings
  # @return [string] one_line_list
  def show_one_line_list(list_items)
    one_line_list = ''
    if list_items.blank?
      one_line_list = '未設定'
    else
      list_items.each { |item| one_line_list += "#{item} / " if item.present? }
      one_line_list
    end
  end

  # @params [BusinessHour] open_status
  # @return [string] open_message
  def show_business_hour(open_status)
    case open_status.category
    when LUNCH_TIME
      open_message(open_status, '前半')
    when DINNER_TIME
      open_message(open_status, '後半')
    end
  end

  # @params [BusinessHour] open_status
  # @params [string] part
  # @return [string]
  def open_message(open_status, part)
    if open_status.is_holiday?
      "#{part}の部：定休"
    else
      "#{part}の部：#{from_open_to_end(open_status.start_at, open_status.end_at)}"
    end
  end

  # @params [string] start_at, end_at
  # @return [string]
  def from_open_to_end(start_at, end_at)
    start_at.present? && end_at.present? ? "#{start_at} 〜 #{end_at}" : '未設定'
  end

  # @params [symbol] caregory
  # @return [Hash]
  def taste_spec(category)
    taste_spec_distribution = Post.group(category).count.sort.to_h
    taste_category = t('enums.post')[category].sort.to_h
    taste_spec_distribution.values.map.with_index do |count, idx|
      [taste_category.values[idx], count]
    end.to_h
  end
end

app/views/jiros/_edit_jiro_navi_bar.html.erb
<div class="edit_header">
  <div class="jiro_name"><%= @jiro.name %></div>
  <div class="jiro_btn">
    <%= link_to jiro_path(@jiro) do %>
      <span class="btn btn-primary">
      <%= "店舗トップ" %></span>
    <% end %>
  <div>
</div>
<br>
<ul id="nav">
  <li><a href="/jiros/<%=jiro_id%>/edit">基礎情報</a></li>
  <li><a href="/jiros/<%=jiro_id%>/business_hours/edit">営業時間</a></li>
  <li><a href="/jiros/<%=jiro_id%>/facilities/edit">店内設備</a></li>
  <li><a href="/jiros/<%=jiro_id%>/menu_items/edit">メニュー</a></li>
</ul>

app/views/jiros/_have_eaten_button.html.erb
<% if jiro.checked_have_eaten_by?(current_jirolian) %>
  <%= link_to jiro_have_eaten_statuses_path(jiro), method: :delete do %>
    <span class="btn btn-success">
    <%= "食べた#{jiro.have_eaten_statuses.count}" %></span>
  <% end %>
<% else %>
  <%= link_to jiro_have_eaten_statuses_path(jiro), method: :post do %>
    <span class="btn btn-secondary">
    <%= "食べた#{jiro.have_eaten_statuses.count}" %></span>
  <% end %>
<% end %>

app/views/jiros/_image_uploader.html.erb
<% if jiro.image? %>
  <%= image_tag jiro.image.thumb.url, class: "jiro-icon" %>
<% else %>
  <%= image_tag "no_image.png", alt: "jiro-icon", size: "100", class: "jiro-icon" %>
<% end %>

app/views/jiros/_jiro_image_icon.html.erb
<% if jiro.image.present? %>
  <%= image_tag jiro.image.url, alt: "jiro-icon", size: "100", class: "jiro-icon" %>
<% else %>
  <%= image_tag 'no_image.png', alt: "default-jiro-icon", size: "100", class: "jiro-icon" %>
<% end %>  

app/views/jiros/_wanna_eat_button.html.erb
<% if jiro.checked_wanna_eat_by?(current_jirolian) %>
  <%= link_to jiro_wanna_eat_statuses_path(jiro), method: :delete do %>
    <span class="btn btn-primary">
    <%= "食べたい#{jiro.wanna_eat_statuses.count}" %></span>
  <% end %>
<% else %>
  <%= link_to jiro_wanna_eat_statuses_path(jiro), method: :post do %>
    <span class="btn btn-secondary">
    <%= "食べたい#{jiro.wanna_eat_statuses.count}" %></span>
  <% end %>
<% end %>

app/views/jiros/edit.html.erb
<%= render 'edit_jiro_navi_bar', jiro_id: @jiro.id %>

<H3>基本情報</H3>
    <%= form_with(model: @jiro, url: jiro_path, local: true) do |f| %>
      <table class="form-table">
        <%= render 'image_uploader', jiro: @jiro %>
        <button type="button" class="btn btn-outline-secondary rounded-pill">
          <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: "image-select-btn" %>
        </button>
        <tr>
          <th><%= f.label :name, "店鋪名" %></th>
          <td><%= f.text_field(:name, class: "name", size: 30, placeholder: '例：ラーメン二郎 三田本店') %></td>
        </tr>
        <tr>
          <th><%= f.label :address, "住所" %></th>
          <td><%= f.text_field(:address, class: "address", size: 40, placeholder: '例：東京都港区三田２丁目１６−４') %></td>
        </tr>
        <tr>
          <th><%= f.label :access, "アクセス" %></th>
          <td><%= f.text_area(:access, class: "access", size: "40*50", placeholder: '例：都営地下鉄 浅草線・三田線「三田駅」A3出口より徒歩8分/JR山手線・京浜東北線「田町駅」三田口（西口）より徒歩10分/三田駅から541m') %></td>
        </tr>
        <tr>
          <th><%= f.label :is_parking_area, "駐車場" %></th>
          <td>
            <label><%= f.radio_button(:is_parking_area, true, class: "is_parking_area") %>あり</label>
            <label><%= f.radio_button(:is_parking_area, false, class: "is_parking_area") %>なし</label>
          </td>
        </tr>
        <tr>
          <th><%= f.label :phone_number, "電話番号" %></th>
          <td><%= f.telephone_field(:phone_number, class: "phone_number", size: 30, placeholder: 'ハイフンなし(半角数字)')%></td>
        </tr>
        <tr>
          <th><%= f.label :hp_url, "Twitter" %></th>
          <td><%= f.url_field(:hp_url, class: "hp_url", size: 30, placeholder: 'https://twitter.com/○○○')%></td>
        </tr>
        <tr>
          <th><%= f.label :seat_count, "店内席数" %></th>
          <td><%= f.number_field(:seat_count, class: "seat_count", min: 0) %>席</td>
        </tr>
        <tr>
          <th><%= f.label :payment_method, "支払方法" %></th>
          <td>
            <label><%= f.radio_button(:payment_method, Jiro.payment_methods.keys[1], class: "payment_method") %>現金のみ</label>
            <label><%= f.radio_button(:payment_method, Jiro.payment_methods.keys[2], class: "payment_method") %>現金以外可</label>
          </td>
        </tr>
        <tr>
          <th><%= f.label :how_to_order, "注文方法" %></th>
          <td>
            <label><%= f.radio_button(:how_to_order, Jiro.how_to_orders.keys[1], class: "how_to_order") %>食券制</label>
            <label><%= f.radio_button(:how_to_order, Jiro.how_to_orders.keys[2], class: "how_to_order") %>注文制</label>
          </td>
        </tr>
        <tr>
          <th><%= f.label :call_timing, "トッピングコール" %></th>
          <td>
            <label><%= f.radio_button(:call_timing, Jiro.call_timings.keys[1], class: "call_timing") %>食券提出時</label>
            <label><%= f.radio_button(:call_timing, Jiro.call_timings.keys[2], class: "call_timing") %>麺茹で上がり時</label>
          </td>
        </tr>
        </table>
        <%= f.submit "更新" %>
    <% end %>

app/views/jiros/google_map.js.erb
let map
let geocoder
const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: <%= @jiro.latitude %>, lng: <%= @jiro.longitude %>},
    zoom: 12,
  });
  marker = new google.maps.Marker({
    position:  {lat: <%= @jiro.latitude %>, lng: <%= @jiro.longitude %> },
    map: map
  });
}

app/views/jiros/new.html.erb
<H3>基本情報</H3>
  <%= form_with(model: @jiro, url: jiros_path, local: true) do |f| %>
    <table class="table">
    <%= render 'image_uploader', jiro: @jiro %>
    <button type="button" class="btn btn-outline-secondary rounded-pill">
      <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: "image-select-btn" %>
    </button>
    <tr>
      <th><%= f.label :name, "店鋪名" %></th>
      <td><%= f.text_field(:name, class: "name", size: 30, placeholder: '例：ラーメン二郎 三田本店') %></td>
    </tr>
    <tr>
      <th><%= f.label :address, "住所" %></th>
      <td><%= f.text_field(:address, class: "address", size: 40, placeholder: '例：東京都港区三田２丁目１６−４') %></td>
    </tr>
    <tr>
      <th><%= f.label :access, "アクセス" %></th>
      <td><%= f.text_area(:access, class: "access", size: "40*50", placeholder: '例：都営地下鉄 浅草線・三田線「三田駅」A3出口より徒歩8分/JR山手線・京浜東北線「田町駅」三田口（西口）より徒歩10分/三田駅から541m') %></td>
    </tr>
    <tr>
      <th><%= f.label :is_parking_area, "駐車場" %></th>
      <td>
        <label><%= f.radio_button(:is_parking_area, true, class: "is_parking_area") %>あり</label>
        <label><%= f.radio_button(:is_parking_area, false, class: "is_parking_area") %>なし</label>
      </td>
    </tr>
    <tr>
      <th><%= f.label :phone_number, "電話番号" %></th>
      <td><%= f.telephone_field(:phone_number, class: "phone_number", size: 30, placeholder: 'ハイフンなし(半角数字)')%></td>
    </tr>
    <tr>
      <th><%= f.label :hp_url, "Twitter" %></th>
      <td><%= f.url_field(:hp_url, class: "hp_url", size: 30, placeholder: 'https://twitter.com/○○○')%></td>
    </tr>
    <tr>
      <th><%= f.label :seat_count, "店内席数" %></th>
      <td><%= f.number_field(:seat_count, class: "seat_count", min: 0) %>席</td>
    </tr>
    <tr>
      <th><%= f.label :payment_method, "支払方法" %></th>
      <td>
        <label><%= f.radio_button(:payment_method, Jiro.payment_methods.keys[0], class: "payment_method", checked: true) %>未設定</label>
        <label><%= f.radio_button(:payment_method, Jiro.payment_methods.keys[1], class: "payment_method") %>現金のみ</label>
        <label><%= f.radio_button(:payment_method, Jiro.payment_methods.keys[2], class: "payment_method") %>現金以外可</label>
      </td>
    </tr>
    <tr>
      <th><%= f.label :how_to_order, "注文方法" %></th>
      <td>
        <label><%= f.radio_button(:how_to_order, Jiro.how_to_orders.keys[0], class: "how_to_order", checked: true) %>未設定</label>
        <label><%= f.radio_button(:how_to_order, Jiro.how_to_orders.keys[1], class: "how_to_order") %>食券制</label>
        <label><%= f.radio_button(:how_to_order, Jiro.how_to_orders.keys[2], class: "how_to_order") %>注文制</label>
      </td>
    </tr>
    <tr>
      <th><%= f.label :call_timing, "トッピングコール" %></th>
      <td>
        <label><%= f.radio_button(:call_timing, Jiro.call_timings.keys[0], class: "call_timing", checked: true) %>未設定</label>
        <label><%= f.radio_button(:call_timing, Jiro.call_timings.keys[1], class: "call_timing") %>食券提出時</label>
        <label><%= f.radio_button(:call_timing, Jiro.call_timings.keys[2], class: "call_timing") %>麺茹で上がり時</label>
      </td>
    </tr>
    </table>
    <%= f.submit "登録" %>
  <% end %>

app/views/jiros/show.html.erb
<%= button_to '食レポ', new_jiro_posts_path(@jiro), method: :get %>
<%= button_to '情報修正', edit_jiro_path(@jiro), method: :get %>

<%= render 'jiros/wanna_eat_button', jiro: @jiro %>
<%= render 'jiros/have_eaten_button', jiro: @jiro %>

<h1>店舗情報</h1>

<ul class="pie_chart">
  <li><%= pie_chart taste_spec(:soup), library: {title: {text: 'スープ'}} %></li>
  <li><%= pie_chart taste_spec(:noodle), library: {title: {text: 'メン'}} %></li>
  <li><%= pie_chart taste_spec(:boiled_vegetable), library: {title: {text: 'ヤサイ'}} %></li>
  <li><%= pie_chart taste_spec(:roasted_pork), library: {title: {text: 'ブタ'}} %></li>
</ul>

<%= render 'jiro_image_icon', jiro: @jiro %>
<div id='google_map'>
  <script>
  let map
  let geocoder
  const display = document.getElementById('display')

  function initMap(){
    geocoder = new google.maps.Geocoder()

    map = new google.maps.Map(document.getElementById('google_map'), {
      center: {lat: <%= @jiro.latitude %>, lng: <%= @jiro.longitude %>},
      zoom: 12,
    });
    marker = new google.maps.Marker({
      position:  {lat: <%= @jiro.latitude %>, lng: <%= @jiro.longitude %> },
      map: map
    });
  }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY']%>&callback=initMap" async defer></script>
</div>


  <h2>基本情報</h2>
    <table class="table">
      <tr><th>店鋪名：</th>
        <td><%= @jiro.name %></td></tr>
      <tr><th>住所：</th>
        <td><%= @jiro.address %></td></tr>
      <tr><th>アクセス：</th>
        <td><%= @jiro.access %></td></tr>
      <tr><th>駐車場：</th>
        <td><%= exist(@jiro.is_parking_area) %></td></tr>
      <tr><th>TEL：</th>
        <td><%= @jiro.phone_number %></td></tr>
      <tr><th>HP/SNS：</th>
        <td><%= link_to('コチラ', @jiro.hp_url) %></td></tr>
      <tr><th>席数：</th>
        <td><%= @jiro.seat_count %></td></tr>
      <tr><th>支払方法：</th>
        <td><%= @jiro.payment_method_i18n %></td></tr>
      <tr><th>注文方法：</th>
        <td><%= @jiro.how_to_order_i18n %></td></tr>
      <tr><th>コールタイミング：</th>
        <td><%= @jiro.call_timing_i18n %></td></tr>
      </tr>
    </table>

  <h2>店内設備</h2>
    <table border="1" style="border-collapse: collapse">
      <tr>
        <th>レンゲ</th>
        <th>ティッシュ</th>
        <th>紙エプロン</th>
        <th>ウォーターサーバー</th>
        <th>ゴミ箱</th>
        <th>自動販売機</th>
        <th>髪留め</th>
        <th>店内待ち数</th>
      </tr>
      <tr>
        <td><%= exist(@facility.is_renge) %></td>
        <td><%= exist(@facility.is_tissue) %></td>
        <td><%= exist(@facility.is_apron) %></td>
        <td><%= exist(@facility.is_water_server) %></td>
        <td><%= exist(@facility.is_trash_box) %></td>
        <td><%= exist(@facility.is_vending_machine) %></td>
        <td><%= exist(@facility.is_hair_tie) %></td>
        <td><%= show_waiting_seat(@facility.in_store_pending) %></td>
      </tr>
    </table>

  <h2>卓上調味料</h2>
    <p style="text-decoration: underline" ><%= show_one_line_list(@table_seasonings) %></p>
      
  <h2>メインメニュー</h2>
    <% if @main_menus.blank? %>
      <%= '未設定' %>
    <% else %>
      <% @main_menus.each do |main_menu| %>
        <table class="table">
        <% if main_menu.name.present? %>
          <tr><th>名称：</th>
            <td><%= main_menu.name %></td></tr>
          <tr><th>価格：</th>
            <td><%= "#{main_menu.price}円" %></td></tr>
          <tr><th>麺の量：</th>
            <td><%= "#{main_menu.noodle_quantity}g" %></td></tr>
          <tr><th>トッピング：</th>
            <td><%= show_one_line_list(@toppings_list[main_menu.id]) %></td></tr>
          <tr><th>備考：</th>
            <td><%= main_menu.note %></td></tr>
          </tr><br>
        <% end %>  
        </table>
      <% end %>
    <% end %>

    <h2>オプションメニュー</h2>
      <% if @option_menus.blank? %>
        <%= '未設定' %>
      <% else %>
        <% @option_menus.each do |option_menu| %>
          <table class='table'>
            <% if option_menu.name.present? %>
              <tr>
                <th><%= option_menu.name %></th>
                <td><%= "#{option_menu.price}円" %></td>
              </tr>
            <% end %>  
          </table>
        <% end %>
      <% end %>

    <h2>店舗補足情報</h2>
      <%= @jiro.information%>
    
    <h2>営業時間</h2>
      <table class="table">
        <% (0..6).each do |wday| %>
          <tr>
            <th><%= "#{%w[日 月 火 水 木 金 土][wday]}曜日" %></th>
            <% if @business_hour_wdays_list[wday] %>
              <% @business_hour_wdays_list[wday].each do |open_status|%>
                <td><%= show_business_hour(open_status) %></td>
              <% end %>
            <% end %>    
          </tr>
        <% end %>
      </table>

    <% if @posts.present? %>
      <%= render 'posts/display_posts', posts: @posts %>
    <% else %>
      <div>この店舗に関する投稿は有りません。</div>  
    <% end %>