config/routes.rb
Rails.application.routes.draw do
  devise_for :jirolians

  root 'top#index'

  get '/search' => 'top#search'
  resources :posts, expect: [:index] do
    resource :favorite_posts, only: [:create, :destroy]
  end

  resources :jiros, except: [:destroy] do
    resource :business_hours, only: [:edit, :update]
    resource :facilities, only: [:edit, :update]
    resource :menu_items, only: [:edit] do
      member do
        patch 'update_main_menu'
        patch 'update_option_menu'
      end
    end
    resource :posts, only: [:new, :create]
    resource :wanna_eat_statuses, only: [:create, :destroy]
    resource :have_eaten_statuses, only: [:create, :destroy]
  end

  # resources :jirolians, only: [:show] do
  #   resources :posts, only: [:show]
  # end

  get '/jirolians/mypage' => 'jirolians#mypage'
  get '/jirolians/:username' => 'jirolians#show'
  get '/jirolians/:username/edit' => 'jirolians#edit'
  patch '/jirolians/:username' => 'jirolians#update'

  resources :relationships, only: [:create, :destroy]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :bigint           not null, primary key
#  boiled_vegetable :integer
#  called           :string(255)
#  content          :text(65535)
#  noodle           :integer
#  roasted_pork     :integer
#  soup             :integer
#  wating_time      :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  jiro_id          :integer
#  jirolian_id      :integer
#
class Post < ApplicationRecord
  has_many :favorite_posts, dependent: :destroy
  belongs_to :jirolian
  belongs_to :jiro

  enum soup: {emulsification: 1, little_emulsification: 2, non_emulsification: 3}
  enum noodle: {soft: 1, little_soft: 2, little_hard: 3, hard: 4}
  enum boiled_vegetable: {tender: 1, tough: 2}
  enum roasted_pork: {crumbly: 1, melted: 2, fatty: 3}

  validates :content, presence: true
  validates :jiro_id, presence: true
  validates :jirolian_id, presence: true

  def favorited_by?(jirolian)
    favorite_posts.where(jirolian_id: jirolian.id).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_jirolian!, only: [:new, :create, :destroy]

  def index
    @posts = Post.all.order(created_at: :DESC)
  end

  # def show
  #   @posts = Post.where(jirolian_id: params[:jirolian_id])
  # end

  def new
    @post = Post.new
  end

  def create
    @jiro = Jiro.find_by_id(params[:jiro_id])
    @post = Post.new(post_params)
    if @post.save
      redirect_to jiro_path(@jiro)
    else
      render :new
    end
  end

  def destroy; end

  private

  def post_params
    params.require(:post).permit(:jirolian_id, :content, :soup, :noodle, :boiled_vegetable, :roasted_pork,
                                 :called).merge(jiro_id: params[:jiro_id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_display_posts.html.erb
<% posts.each do |post| %>
  <div>
    <%= render 'jirolians/jirolian_image_icon', jirolian: post.jirolian %>
    <a href="/jirolians/<%= post.jirolian.username %>"><%= post.jirolian.username %></a><br>
    <%= post.created_at.strftime('%Y/%m/%d') %>訪問<br>
    <a href="/jiros/<%= post.jiro.id %>"><%= post.jiro.name %></a><br>
    <p><%= post.content %></p>
    <p><%= "並び時間：#{post.wating_time}分" if post.wating_time.present? %></p>
    <p><%= "トッピング：#{post.called}" if post.called.present? %></p>
    <% if jirolian_signed_in? %>
      <div id="favorite_post_buttons_<%= post.id %>">
        <%= render 'favorite_posts/favorite_button', { post: post } %>
      </div>
    <% else %>
      <%= link_to new_jirolian_session_path do %>
        <span class="far fa-heart" aria-hidden="true" style="color: #8899a6;"></span>
      <% end %>
      <%= post.favorite_posts.count %>
    <% end%>
  </div>
  <hr style="border-bottom: 3px double #8899a6;">
<% end %>

app/views/posts/index.html.erb
<% if @posts.present? %>
  <%= render 'display_posts', posts: @posts, current_jirolian: current_jirolian %>
<% else %>
  <div>投稿は有りません。</div>
<% end %>

app/views/posts/new.html.erb
<%= form_with(model: @post, url: jiro_posts_path, local: true) do |f| %>
  <table class="table">
  <tr>
    <th><%= f.label :content %></th>
    <td><%= f.text_area(:content, class: "content", size: "40*50") %></td>
  </tr>
  <tr>
    <th><%= f.label :wating_time, "並んだ時間" %></th>
    <td>約<%= f.number_field(:wating_time, class: "wating_time") %>分</td>
  </tr>
  <tr>
    <th><%= f.label :called, "トッピング" %></th>
    <td><%= f.text_field(:called, class: "called", size: "30", placeholder: '例：ヤサイマシアブラカラメ') %></td>
  </tr>
  <tr>
    <th><%= f.label :soup, "スープ" %></th>
    <td>
      <label><%= f.radio_button(:soup, Post.soups.keys[0], class: "soup") %>非乳化</label>
      <label><%= f.radio_button(:soup, Post.soups.keys[1], class: "soup") %>微乳化</label>
      <label><%= f.radio_button(:soup, Post.soups.keys[2], class: "soup") %>乳化</label>
    </td>
  </tr>
  <tr>
    <th><%= f.label :noodle, "メン" %></th>
    <td>
      <label><%= f.radio_button(:noodle, Post.noodles.keys[0], class: "noodle") %>デロ</label>
      <label><%= f.radio_button(:noodle, Post.noodles.keys[1], class: "noodle") %>ややデロ</label>
      <label><%= f.radio_button(:noodle, Post.noodles.keys[2], class: "noodle") %>やや固</label>
      <label><%= f.radio_button(:noodle, Post.noodles.keys[3], class: "noodle") %>バキボキ</label>
    </td>
  </tr>
  <tr>
    <th><%= f.label :boiled_vegetable, "ヤサイ" %></th>
    <td>
      <label><%= f.radio_button(:boiled_vegetable, Post.boiled_vegetables.keys[0], class: "boiled_vegetable") %>クタ</label>
      <label><%= f.radio_button(:boiled_vegetable, Post.boiled_vegetables.keys[1], class: "boiled_vegetable") %>シャキ</label>
    </td>
  </tr>
  <tr>
    <th><%= f.label :roasted_pork, "ブタ" %></th>
    <td>
      <label><%= f.radio_button(:roasted_pork, Post.roasted_porks.keys[0], class: "roasted_pork") %>パサ</label>
      <label><%= f.radio_button(:roasted_pork, Post.roasted_porks.keys[1], class: "roasted_pork") %>ホロ</label>
      <label><%= f.radio_button(:roasted_pork, Post.roasted_porks.keys[2], class: "roasted_pork") %>ブリンブリン</label>
    </td>
  </tr>
  <td><%= f.hidden_field(:jirolian_id, :value => current_jirolian.id)%></td>
  </table>
  <%= f.submit "登録" %>
<% end %>

app/views/posts/show.html.erb
<% @posts.each do |post| %>
  <%= post.content %>
<% end %>