config/routes.rb
Rails.application.routes.draw do
  devise_for :jirolians

  root 'top#index'

  get '/search' => 'top#search'
  resources :posts, expect: [:index] do
    resource :favorite_posts, only: [:create, :destroy]
  end

  resources :jiros, except: [:destroy] do
    resource :business_hours, only: [:edit, :update]
    resource :facilities, only: [:edit, :update]
    resource :menu_items, only: [:edit] do
      member do
        patch 'update_main_menu'
        patch 'update_option_menu'
      end
    end
    resource :posts, only: [:new, :create]
    resource :wanna_eat_statuses, only: [:create, :destroy]
    resource :have_eaten_statuses, only: [:create, :destroy]
  end

  # resources :jirolians, only: [:show] do
  #   resources :posts, only: [:show]
  # end

  get '/jirolians/mypage' => 'jirolians#mypage'
  get '/jirolians/:username' => 'jirolians#show'
  get '/jirolians/:username/edit' => 'jirolians#edit'
  patch '/jirolians/:username' => 'jirolians#update'

  resources :relationships, only: [:create, :destroy]
end

app/models/jirolian.rb
# == Schema Information
#
# Table name: jirolians
#
#  id                     :bigint           not null, primary key
#  approved_favorited     :boolean
#  birth_date             :datetime
#  confirmation_sent_at   :datetime
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  failed_attempts        :integer          default(0), not null
#  gender                 :integer
#  home_jiro              :string(255)
#  hp_url                 :string(255)
#  image                  :string(255)
#  introduction           :text(65535)
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string(255)
#  locked_at              :datetime
#  provider               :string(255)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  sign_in_count          :integer          default(0), not null
#  uid                    :string(255)
#  unconfirmed_email      :string(255)
#  unlock_token           :string(255)
#  username               :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_jirolians_on_confirmation_token    (confirmation_token) UNIQUE
#  index_jirolians_on_email                 (email) UNIQUE
#  index_jirolians_on_reset_password_token  (reset_password_token) UNIQUE
#  index_jirolians_on_unlock_token          (unlock_token) UNIQUE
#
class Jirolian < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :favorite_posts, dependent: :destroy
  has_many :wanna_eat_statuses, dependent: :destroy
  has_many :have_eaten_statuses, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :jirolian
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable, :omniauthable, omniauth_providers: [:twitter]

  mount_uploader :image, ImageUploader

  enum gender: {male: 0, female: 1, unanswered: 2}

  validates :username, presence: true

  def follow(other_jirolian)
    relationships.find_or_create_by(follow_id: other_jirolian.id) unless self == other_jirolian
  end

  def unfollow(other_jirolian)
    relationship = relationships.find_by(follow_id: other_jirolian.id)
    relationship.destroy if relationship
  end

  def following?(other_jirolian)
    followings.include?(other_jirolian)
  end
end

app/controllers/jirolians_controller.rb
class JiroliansController < ApplicationController
  before_action :authenticate_jirolian!, except: [:show]
  before_action :set_jirolian, except: [:mypage]

  def mypage
    redirect_to "/jirolians/#{current_jirolian.username}"
  end

  def show
    @posts = Post.where(jirolian_id: @jirolian.id)

    wanna_eat_jiro_ids = @jirolian.wanna_eat_statuses.pluck(:jiro_id)
    @wanna_eat_jiros = Jiro.where(id: wanna_eat_jiro_ids)

    have_eaten_jiro_ids = @jirolian.have_eaten_statuses.pluck(:jiro_id)
    @have_eaten_jiros = Jiro.where(id: have_eaten_jiro_ids)

    followed_ids = Relationship.where(jirolian_id: @jirolian.id).pluck(:follow_id)
    @followed_jirolians = Jirolian.where(id: followed_ids)

    follower_ids = Relationship.where(follow_id: @jirolian.id).pluck(:jirolian_id)
    @follower_jirolians = Jirolian.where(id: follower_ids)
  end

  def edit
    redirect_to "/jirolians/#{@jirolian.username}" unless @jirolian == current_jirolian
  end

  def update
    if current_jirolian.update(jirolian_params)
      flash.notice = '更新が完了しました。'
      redirect_to "/jirolians/#{current_jirolian.username}"
    else
      flash.notice = '更新に失敗しました。'
      redirect_to "/jirolians/#{current_jirolian.username}/edit"
    end
  end

  private

  def set_jirolian
    @jirolian = Jirolian.find_by(username: params[:username])
  end

  def jirolian_params
    params[:jirolian].permit(:username, :gender, :birth_date, :home_jiro, :introduction, :hp_url,
                             :approved_favorited, :image)
  end
end

app/helpers/jirolians_helper.rb
module JiroliansHelper
end

app/views/jirolians/_follow_button.html.erb
<% unless current_jirolian == jirolian %>
  <% if current_jirolian.following?(jirolian) %>
    <%= form_with(model: current_jirolian.relationships.find_by(follow_id: jirolian.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, jirolian.id %>
      <%= f.submit 'フォローを外す', class: 'btn btn-info' %>
    <% end %>
  <% else %>
    <%= form_with(model: current_jirolian.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, jirolian.id %>
      <%= f.submit 'フォロー', class: 'btn btn-outline-info' %>
    <% end %>
  <% end %>
<% end %>

app/views/jirolians/_image_uploader.html.erb
<% if jirolian.image? %>
  <%= image_tag jirolian.image.thumb.url, class: "jirolian-icon" %>
<% else %>
  <%= image_tag "default.jpg", alt: "jirolian-icon", size: "50", class: "jirolian-icon" %>
<% end %>

app/views/jirolians/_jirolian_image_icon.html.erb
<% if jirolian.image.present? %>
  <%= image_tag jirolian.image.url, alt: "jirolian-icon", size: "50", class: "jirolian-icon" %>
<% else %>
  <%= image_tag 'default.jpg', alt: "default-jirolian-icon", size: "50", class: "jirolian-icon" %>
<% end %>  

app/views/jirolians/edit.html.erb
<%= form_with(model: @jirolian, url: "/jirolians/#{@jirolian.username}", local: true) do |f| %>
  <table class="form-table">
    <%= render 'image_uploader', jirolian: @jirolian %>
    <button type="button" class="btn btn-outline-secondary rounded-pill">
      <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: "image-select-btn" %>
    </button>
    <tr>
      <th><%= f.label :username, "ユーザーネーム" %></th>
      <td><%= f.text_field(:username, class: "username", size: 30) %></td>
    </tr>
    <tr>
      <th><%= f.label :gender, "ご性別" %></th>
      <td>
        <label><%= f.radio_button(:gender, Jirolian.genders.keys[0], class: "gender") %>男性</label>
        <label><%= f.radio_button(:gender, Jirolian.genders.keys[1], class: "gender") %>女性</label>
        <label><%= f.radio_button(:gender, Jirolian.genders.keys[2], class: "gender") %>未回答</label>
      </td>
    </tr>
    <tr>
      <th><%= f.label :birth_date, "生年月日" %></th>
      <td><%= f.date_select(:birth_date, class: "birth_date", use_month_numbers: true, start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1989, 1, 1)) %>
      </td>
    </tr>
    <tr>
      <th><%= f.label :home_jiro, "ホームジロウ" %></th>
      <td><%= f.text_field(:home_jiro, class: "home_jiro", size: 30) %></td>
    </tr>    
    <tr>
      <th><%= f.label :introduction, "自己紹介" %></th>
      <td><%= f.text_field(:introduction, class: "introduction", size: "40*50", placeholder: 'いつもヤサイマシマシをモットーにしています。') %></td>
    </tr>
      <th><%= f.label :hp_url, "HP/SNS" %></th>
      <td><%= f.url_field(:hp_url, class: "hp_sns", placeholder: 'https://twitter.com/○○○')%></td>
    </tr>
      <th><%= f.label :approved_favorited, "お気に入られ" %></th>
      <td>
        <label><%= f.radio_button(:approved_favorited, true, class: "approved_favorited") %>許可する</label>
        <label><%= f.radio_button(:approved_favorited, false, class: "approved_favorited") %>許可しない</label>
        <p>※「許可する」では他ユーザーからの「お気に入り」を許可します。</p>
        <p>※「許可しない」に更新すると現在のお気に入られがすべて解除されます。</p>
      </td>
    </tr>
    </table>
    <%= f.submit "更新" %>
<% end %>

app/views/jirolians/show.html.erb
<%= javascript_pack_tag 'jirolian/show' %>

<% if jirolian_signed_in? && @jirolian == current_jirolian %>
  <h1>マイページ</h1>
<% else %>
  <h1>ユーザーページ</h1>
<% end %>

<%= render 'jirolian_image_icon', jirolian: @jirolian %>

<h2><%= @jirolian.username %></h2>
  <table class="table">
    <tr><th>登録日：</th>
      <td><%= @jirolian.created_at.strftime('%Y.%m.%d') %></td></tr>
    <tr><th>ホーム：</th>
      <td><%= @jirolian.home_jiro %></td></tr>
    <tr><th>自己紹介：</th>
      <td><%= @jirolian.introduction %></td></tr>
    <tr><th>HP/SNS：</th>
      <td><a href="<%=@jirolian.hp_url %>"><%= @jirolian.hp_url %></td></tr>
  </table>

<% if jirolian_signed_in? %>
  <%= render 'follow_button', jirolian: @jirolian, current_jirolian: current_jirolian %>
<% end %>

<% if jirolian_signed_in? && @jirolian == current_jirolian %>
  <div><%= button_to "編集", "/jirolians/#{current_jirolian.username}/edit", method: :get %></div>
<% end %>

<br>

<div class="container">
  <ul class="tab-list">
    <li class="tab tab-active">ジ活</li>
    <li class="tab">食べたい</li>
    <li class="tab">食べた</li>
    <li class="tab">フォロー(<%= "#{@followed_jirolians.count}" %>)</li>
    <li class="tab">フォロワー(<%= "#{@follower_jirolians.count}" %>)</li>
  </ul>
  <div class="tabbox-contents">
    <div class="tabbox box-show">
      <% @posts.each do |post| %>
        <div>
          <%= render 'jirolian_image_icon', jirolian: @jirolian %>
          <a href="/jirolians/<%= post.jirolian.username %>"><%= post.jirolian.username %></a><br>
          <%= post.created_at.strftime('%Y/%m/%d') %>訪問<br>
          <a href="/jiros/<%= post.jiro.id %>"><%= post.jiro.name %></a><br>
          <p><%= post.content %></p>
          <p><%= "並び時間：#{post.wating_time}分" if post.wating_time.present? %></p>
          <p><%= "トッピング：#{post.called}" if post.called.present? %></p>
          <% if jirolian_signed_in? %>
            <div id="favorite_post_buttons_<%= post.id %>">
              <%= render 'favorite_posts/favorite_button', { jirolian: current_jirolian, post: post } %>
            </div>
          <% else %>
            <%= link_to new_jirolian_session_path do %>
              <span class="" style="color: #8899a6;"></span>
            <% end %>
            <%= post.favorite_posts.count %><
          <% end%>
        </div>
        <hr style="border-bottom: 3px double #8899a6;">
      <% end %>
    </div>
    <div class="tabbox">
      <% @wanna_eat_jiros.each do |jiro| %>
        <table>
          <tr><%=link_to jiro.name, jiro_path(jiro) %></tr>
          <td><%= jiro.address %></td>
        </table>
        <hr style="border-bottom: 3px double #8899a6;">
      <% end %>
    </div>
    <div class="tabbox">
      <% @have_eaten_jiros.each do |jiro| %>
        <table>
          <tr><%=link_to jiro.name, jiro_path(jiro) %></tr>
          <td><%= jiro.address %></td>
        </table>
        <hr style="border-bottom: 3px double #8899a6;">
      <% end %>
    </div>
    <div class="tabbox">
      <% @followed_jirolians.each do |jirolian| %>
        <table>
          <tr><%= render 'jirolian_image_icon', jirolian: jirolian %></tr>
          <tr><%= link_to jirolian.username, "/jirolians/#{jirolian.username}" %></tr>
        </table>
        <hr style="border-bottom: 3px double #8899a6;">
      <% end %>
    </div>
    <div class="tabbox">
      <% @follower_jirolians.each do |jirolian| %>
        <table>
          <tr><%= render 'jirolian_image_icon', jirolian: jirolian %></tr>
          <tr><%= link_to jirolian.username, "/jirolians/#{jirolian.username}" %></tr>
        </table>
        <hr style="border-bottom: 3px double #8899a6;">
      <% end %>      
    </div>        
  </div>
</div>