config/routes.rb
Rails.application.routes.draw do
  devise_for :jirolians

  root 'top#index'

  get '/search' => 'top#search'
  resources :posts, expect: [:index] do
    resource :favorite_posts, only: [:create, :destroy]
  end

  resources :jiros, except: [:destroy] do
    resource :business_hours, only: [:edit, :update]
    resource :facilities, only: [:edit, :update]
    resource :menu_items, only: [:edit] do
      member do
        patch 'update_main_menu'
        patch 'update_option_menu'
      end
    end
    resource :posts, only: [:new, :create]
    resource :wanna_eat_statuses, only: [:create, :destroy]
    resource :have_eaten_statuses, only: [:create, :destroy]
  end

  # resources :jirolians, only: [:show] do
  #   resources :posts, only: [:show]
  # end

  get '/jirolians/mypage' => 'jirolians#mypage'
  get '/jirolians/:username' => 'jirolians#show'
  get '/jirolians/:username/edit' => 'jirolians#edit'
  patch '/jirolians/:username' => 'jirolians#update'

  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no">

      <title>JiroTabetai</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">Company name</h5>
        <nav class="my-2 my-md-0 mr-md-3">
          <% if jirolian_signed_in? %>
            <div class="dropdown">
              <div class="nav-link" id="dropdownMenuButton button_group" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= render './jirolians/jirolian_image_icon', jirolian: current_jirolian %>
              </div>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <%= link_to 'マイページ', '/jirolians/mypage', class: 'nav-link dropdown-item' %>
                <%= link_to '施設登録', new_jiro_path, class: 'nav-link dropdown-item' %>
                <%= link_to 'ログアウト', destroy_jirolian_session_path, method: :delete, class: 'nav-link dropdown-item' %>
                <div class="dropdown-divider"></div>
              </div>
            </div>    
          <% else %>
            <%= link_to 'サインアップ', new_jirolian_registration_path %>
            <%= link_to 'ログイン', new_jirolian_session_path %>
          <% end %>
        </nav>
      </div>
      <div class="notifications">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: key) %>
        <% end %>
      </div>
    <%= yield %>
  </body>
</html>